### ISSUE TITLE
Another spot where /in stopped working

### ISSUE THREAD

**Issue by CPOBob097** [funkydude/SlashIn#4] opened 2020-01-15 01:16 UTC
I think this might be related to the WoW Classic update earlier where /in stopped working. Here is my macro:
/cast Dismiss Pet
/in 4 /run SendChatMessage(UnitName("pet")..", go play!","say")

I get the error that an addon has failed.  The line where /in is used does not happen.  Just checking if this is the same issue as others have had where commands have become restricted.  The macro does work without the /in being used, just not delayed like I like.

Thanks for any input you can provide.

**Comment by funkydude** [comment] 2020-01-15 02:41
Duplicate of #3

**Closed as completed by funkydude** 2020-01-15 02:41 UTC
